### ISSUE TITLE
Fastify incompatibility

### ISSUE THREAD

**Issue by StarpTech** [NaturalIntelligence/fastify-xml-body-parser#2]
Hi, you can't pass an array [here](https://github.com/NaturalIntelligence/fastify-xml-body-parser/blob/master/index.js#L46) it should throw in the current fastify version. I'm going to create a PR to support the array syntax.

**Comment by StarpTech** [comment]
Nevermind, you check the type before you call the method. That's fine but can be improved when https://github.com/fastify/fastify/pull/967 is merged 😄

**Comment by amitguptagwl** [comment]
Sure.
