### ISSUE TITLE
Auto convert the number

### ISSUE THREAD

**Issue by phongdo00** [NaturalIntelligence/fastify-xml-body-parser#22]
My xml request is 000 and automate convert to 0, it cause some error when comparing
e.g: the requets: `<result>000</result>` but after parse with fastify-xml-body-parse I got `{ result: 0}`
Any ideal or parse options to fix this, many thanks

**Comment by amitguptagwl** [comment]
please str-num library for different combinations. Or you can use tagValueProcessor and othre relevant functions. Please check docs once
