### ISSUE TITLE
A problem occurs when a pure numeric string exceeds a certain length

### ISSUE THREAD

**Issue by wang-weifeng** [NaturalIntelligence/fastify-xml-body-parser#3]
After viewing the source code, I found that adding "parseTrueNumberOnly: true" to the configuration can solve

In the fastify project, the complete thing of app.js is as follows:
“fastify.register(require('fastify-xml-body-parser'), { parseTrueNumberOnly: true })”

**Comment by amitguptagwl** [comment]
Sorry, I couldn't understand your concern. As this library is based on Fast-XML-Parser, all the options expected by Fast-XML-Parser can be passed to control the result.
